### PR TITLE
Add reject lines to policy

### PR DESCRIPTION
**Pull request by m0jeda**
Case: https://greenchef.atlassian.net/browse/FWK-289

### CODE REVIEW

**Comment by bearfact** [comment]
@m0jeda bump the version number also

**Comment by m0jeda** [comment]
> @m0jeda bump the version number also

in package.json? and/or manifest.js?

**Comment by bearfact** [comment]
> in package.json? and/or manifest.js?

both

**Comment by m0jeda** [comment]
> > in package.json? and/or manifest.js?
> 
> both

updated

**Pull request merged**
